// New species to append to FUNGI array
// These entries are in the correct format for the Fungus interface
// Run scripts/append_species.py to insert them into fungi.ts

export const NEW_SPECIES = [
  // ── More Agaricales ───────────────────────────────────────────────────────
  {
    id: "macrolepiota-procera",
    scientificName: "Macrolepiota procera",
    commonName: "Parasol Mushroom",
    aliases: ["Parasol", "Tall Lepiota"],
    synonyms: ["Lepiota procera"],
    taxonomy: { kingdom: "Fungi", phylum: "Basidiomycota", class: "Agaricomycetes", order: "Agaricales", family: "Agaricaceae", genus: "Macrolepiota", species: "procera" },
    edibility: "choice",
    ecology: "saprotrophic",
    habitat: "Woodland edges, meadows, roadsides, and pastures",
    naRange: "Eastern North America; introduced in Pacific Northwest",
    morphology: { capShape: "Egg-shaped opening to flat, brown scaly cap on tall stalk with snakeskin pattern", gillAttachment: "Free", sporeColor: "White", hasRing: true, hasVolva: false },
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Macrolepiota_procera.jpg/400px-Macrolepiota_procera.jpg",
    imageAttribution: "© Archenzo / Wikimedia Commons CC-BY-SA",
    crossSectionUrl: null,
    gbifId: 2534714,
    rarity: 35,
    fame: 65,
    difficulty: "medium",
    funFact: "One of the tallest mushrooms in Europe — individual specimens can reach 40 cm tall with a cap diameter of 30 cm.",
  },
  {
    id: "galerina-marginata",
    scientificName: "Galerina marginata",
    commonName: "Deadly Skullcap",
    aliases: ["Autumn Skullcap", "Deadly Galerina"],
    synonyms: ["Galerina autumnalis"],
    taxonomy: { kingdom: "Fungi", phylum: "Basidiomycota", class: "Agaricomycetes", order: "Agaricales", family: "Strophariaceae", genus: "Galerina", species: "marginata" },
    edibility: "deadly",
    ecology: "saprotrophic",
    habitat: "On decaying conifer logs and wood chips, often in clusters",
    naRange: "Widespread across North America; very common in Pacific Northwest",
    morphology: { capShape: "Convex, tawny-brown, hygrophanous; ring present; rusty-brown spore print", gillAttachment: "Adnate", sporeColor: "Rusty brown", hasRing: true, hasVolva: false },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/13948/medium.jpg",
    imageAttribution: "© Jason Hollinger / iNaturalist CC-BY",
    crossSectionUrl: null,
    gbifId: 4934557,
    rarity: 30,
    fame: 55,
    difficulty: "medium",
    funFact: "Contains the same deadly amatoxins as the Death Cap; frequently confused with the edible Kuehneromyces mutabilis — a mistake that kills.",
  },
  {
    id: "lepista-nuda",
    scientificName: "Lepista nuda",
    commonName: "Wood Blewit",
    aliases: ["Blewit", "Blue Leg", "Blue Stalk"],
    synonyms: ["Clitocybe nuda", "Tricholoma nudum"],
    taxonomy: { kingdom: "Fungi", phylum: "Basidiomycota", class: "Agaricomycetes", order: "Agaricales", family: "Tricholomataceae", genus: "Lepista", species: "nuda" },
    edibility: "choice",
    ecology: "saprotrophic",
    habitat: "Mixed and deciduous woodland, gardens, compost heaps; often in leaf litter",
    naRange: "Widespread across North America; common in late autumn",
    morphology: { capShape: "Convex to flat, violet-lilac to buff-brown, smooth; lilac gills and stalk", gillAttachment: "Adnate", sporeColor: "Pale pink", hasRing: false, hasVolva: false },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/34059/medium.jpg",
    imageAttribution: "© Amadej Trnkoczy / iNaturalist CC-BY-NC",
    crossSectionUrl: null,
    gbifId: 2534813,
    rarity: 35,
    fame: 55,
    difficulty: "medium",
    funFact: "One of few mushrooms where the entire fruiting body — cap, gills, and stalk — is blue-violet when fresh; the color fades with age.",
  },
  {
    id: "clitocybe-nebularis",
    scientificName: "Clitocybe nebularis",
    commonName: "Cloudy Funnel",
    aliases: ["Clouded Agaric", "Cloud Funnel"],
    synonyms: ["Lepista nebularis"],
    taxonomy: { kingdom: "Fungi", phylum: "Basidiomycota", class: "Agaricomycetes", order: "Agaricales", family: "Tricholomataceae", genus: "Clitocybe", species: "nebularis" },
    edibility: "inedible",
    ecology: "saprotrophic",
    habitat: "Deciduous and mixed woodland, often in large rings in leaf litter",
    naRange: "Widespread across North America",
    morphology: { capShape: "Convex with inrolled margin, pale grey-brown with white pruina; gills crowded, decurrent", gillAttachment: "Decurrent", sporeColor: "Pale cream", hasRing: false, hasVolva: false },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/47028/medium.jpg",
    imageAttribution: "© Amadej Trnkoczy / iNaturalist CC-BY-NC",
    crossSectionUrl: null,
    gbifId: 2534738,
    rarity: 30,
    fame: 35,
    difficulty: "hard",
    funFact: "Its strong, sweet-soapy smell is distinctive and off-putting; it is also often parasitized by the small fungus Volvariella surrecta.",
  },
  {
    id: "mycena-galericulata",
    scientificName: "Mycena galericulata",
    commonName: "Common Bonnet",
    aliases: ["Toque Mycena"],
    synonyms: [],
    taxonomy: { kingdom: "Fungi", phylum: "Basidiomycota", class: "Agaricomycetes", order: "Agaricales", family: "Mycenaceae", genus: "Mycena", species: "galericulata" },
    edibility: "inedible",
    ecology: "saprotrophic",
    habitat: "Clustered on dead hardwood stumps and logs",
    naRange: "Very common across North America",
    morphology: { capShape: "Bell-shaped, grey-brown with striate margin; crowded pale gills", gillAttachment: "Adnate with decurrent tooth", sporeColor: "White", hasRing: false, hasVolva: false },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/21030/medium.jpg",
    imageAttribution: "© Jason Hollinger / iNaturalist CC-BY",
    crossSectionUrl: null,
    gbifId: 2534987,
    rarity: 10,
    fame: 25,
    difficulty: "hard",
    funFact: "One of the most abundant wood-rotting species in temperate forests; a single stump may host hundreds of caps.",
  },
  {
    id: "inocybe-geophylla",
    scientificName: "Inocybe geophylla",
    commonName: "White Fibrecap",
    aliases: ["Earthy Inocybe", "Common White Inocybe"],
    synonyms: [],
    taxonomy: { kingdom: "Fungi", phylum: "Basidiomycota", class: "Agaricomycetes", order: "Agaricales", family: "Inocybaceae", genus: "Inocybe", species: "geophylla" },
    edibility: "toxic",
    ecology: "mycorrhizal",
    habitat: "Deciduous and conifer woodlands, on paths and in grass near trees",
    naRange: "Common across North America",
    morphology: { capShape: "Conical to flat, white, silky-fibrous; gills initially white, browning", gillAttachment: "Adnate", sporeColor: "Brown", hasRing: false, hasVolva: false },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/31023/medium.jpg",
    imageAttribution: "© Amadej Trnkoczy / iNaturalist CC-BY-NC",
    crossSectionUrl: null,
    gbifId: 2534659,
    rarity: 25,
    fame: 30,
    difficulty: "hard",
    funFact: "Contains muscarine in concentrations high enough to cause cholinergic poisoning; all white-capped Inocybe species should be treated as toxic.",
  },
  {
    id: "entoloma-sinuatum",
    scientificName: "Entoloma sinuatum",
    commonName: "Livid Pinkgill",
    aliases: ["Lead Poisoner", "Livid Entoloma"],
    synonyms: ["Entoloma lividum", "Rhodophyllus sinuatus"],
    taxonomy: { kingdom: "Fungi", phylum: "Basidiomycota", class: "Agaricomycetes", order: "Agaricales", family: "Entolomataceae", genus: "Entoloma", species: "sinuatum" },
    edibility: "toxic",
    ecology: "mycorrhizal",
    habitat: "Deciduous woodland, especially with oak and beech, on calcareous soils",
    naRange: "Eastern North America; primarily a European species",
    morphology: { capShape: "Broadly convex, ivory to grey-white; gills initially yellowish, becoming pink", gillAttachment: "Sinuate", sporeColor: "Pink", hasRing: false, hasVolva: false },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/76490/medium.jpg",
    imageAttribution: "© Amadej Trnkoczy / iNaturalist CC-BY-NC",
    crossSectionUrl: null,
    gbifId: 2534583,
    rarity: 45,
    fame: 35,
    difficulty: "hard",
    funFact: "One of the most poisonous European fungi — responsible for severe gastroenteritis outbreaks when confused with edible species.",
  },
  {
    id: "tricholoma-terreum",
    scientificName: "Tricholoma terreum",
    commonName: "Grey Knight",
    aliases: ["Dirty Tricholoma", "Grey Cavalier"],
    synonyms: [],
    taxonomy: { kingdom: "Fungi", phylum: "Basidiomycota", class: "Agaricomycetes", order: "Agaricales", family: "Tricholomataceae", genus: "Tricholoma", species: "terreum" },
    edibility: "edible",
    ecology: "mycorrhizal",
    habitat: "Conifer forests, especially under pine and spruce",
    naRange: "Northern and western North America",
    morphology: { capShape: "Convex to flat, grey with dark fibrous scales; white gills", gillAttachment: "Sinuate", sporeColor: "White", hasRing: false, hasVolva: false },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/53340/medium.jpg",
    imageAttribution: "© Amadej Trnkoczy / iNaturalist CC-BY-NC",
    crossSectionUrl: null,
    gbifId: 2534816,
    rarity: 30,
    fame: 30,
    difficulty: "hard",
    funFact: "Formerly considered a good edible, but recent research suggests some populations contain toxins — caution is now advised.",
  },
  {
    id: "stropharia-aeruginosa",
    scientificName: "Stropharia aeruginosa",
    commonName: "Verdigris Roundhead",
    aliases: ["Blue-green Stropharia", "Green Roundhead"],
    synonyms: [],
    taxonomy: { kingdom: "Fungi", phylum: "Basidiomycota", class: "Agaricomycetes", order: "Agaricales", family: "Strophariaceae", genus: "Stropharia", species: "aeruginosa" },
    edibility: "toxic",
    ecology: "saprotrophic",
    habitat: "Woodland, grassland, gardens, on soil or decaying wood",
    naRange: "Widespread across North America",
    morphology: { capShape: "Convex, vivid blue-green with white veil remnants; slimy when wet", gillAttachment: "Adnate", sporeColor: "Purple-brown", hasRing: true, hasVolva: false },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/27043/medium.jpg",
    imageAttribution: "© Amadej Trnkoczy / iNaturalist CC-BY-NC",
    crossSectionUrl: null,
    gbifId: 2534440,
    rarity: 35,
    fame: 40,
    difficulty: "hard",
    funFact: "Its startling blue-green color comes from a unique pigment — the cap fades to yellow with age as the pigment degrades.",
  },
  {
    id: "kuehneromyces-mutabilis",
    scientificName: "Kuehneromyces mutabilis",
    commonName: "Sheathed Woodtuft",
    aliases: ["Brown Stew Fungus", "Two-toned Woodtuft"],
    synonyms: ["Pholiota mutabilis"],
    taxonomy: { kingdom: "Fungi", phylum: "Basidiomycota", class: "Agaricomycetes", order: "Agaricales", family: "Strophariaceae", genus: "Kuehneromyces", species: "mutabilis" },
    edibility: "choice",
    ecology: "saprotrophic",
    habitat: "Clustered on decaying stumps and logs of deciduous trees",
    naRange: "Widespread across North America",
    morphology: { capShape: "Convex, hygrophanous — dark brown when wet, drying pale tan from center outward", gillAttachment: "Adnate", sporeColor: "Rusty brown", hasRing: true, hasVolva: false },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/42130/medium.jpg",
    imageAttribution: "© Amadej Trnkoczy / iNaturalist CC-BY-NC",
    crossSectionUrl: null,
    gbifId: 2534419,
    rarity: 30,
    fame: 35,
    difficulty: "hard",
    funFact: "Dangerously confused with the deadly Galerina marginata — both are brown, ringed, and grow in clusters on wood.",
  },
  {
    id: "volvariella-volvacea",
    scientificName: "Volvariella volvacea",
    commonName: "Paddy Straw Mushroom",
    aliases: ["Straw Mushroom", "Rice Straw Mushroom"],
    synonyms: [],
    taxonomy: { kingdom: "Fungi", phylum: "Basidiomycota", class: "Agaricomycetes", order: "Agaricales", family: "Pluteaceae", genus: "Volvariella", species: "volvacea" },
    edibility: "choice",
    ecology: "saprotrophic",
    habitat: "On rice straw and other agricultural waste in tropical regions; widely cultivated",
    naRange: "Tropical and subtropical; cultivated in southeastern US",
    morphology: { capShape: "Grey-brown egg emerging from white volva; flat to convex at maturity; pink gills", gillAttachment: "Free", sporeColor: "Pink", hasRing: false, hasVolva: true },
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Volvariella_volvacea_EM.jpg/400px-Volvariella_volvacea_EM.jpg",
    imageAttribution: "© EEKA / Wikimedia Commons CC-BY-SA",
    crossSectionUrl: null,
    gbifId: 2534949,
    rarity: 40,
    fame: 55,
    difficulty: "medium",
    funFact: "The third most cultivated mushroom globally; it must be eaten when immature (still in the egg stage) as it resembles deadly Amanitas when mature.",
  },
  {
    id: "panaeolus-cinctulus",
    scientificName: "Panaeolus cinctulus",
    commonName: "Banded Mottlegill",
    aliases: ["Weed Panaeolus", "Subbs"],
    synonyms: ["Panaeolus subbalteatus"],
    taxonomy: { kingdom: "Fungi", phylum: "Basidiomycota", class: "Agaricomycetes", order: "Agaricales", family: "Bolbitiaceae", genus: "Panaeolus", species: "cinctulus" },
    edibility: "psychoactive",
    ecology: "saprotrophic",
    habitat: "Dung-enriched grassland, compost, and manured soil",
    naRange: "Widespread across North America",
    morphology: { capShape: "Convex, hygrophanous cinnamon-brown drying tan; dark marginal band when moist", gillAttachment: "Adnate", sporeColor: "Black", hasRing: false, hasVolva: false },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/29830/medium.jpg",
    imageAttribution: "© Alan Rockefeller / iNaturalist CC-BY",
    crossSectionUrl: null,
    gbifId: 2534389,
    rarity: 30,
    fame: 35,
    difficulty: "hard",
    funFact: "Contains psilocybin; one of the most widespread psilocybin-containing fungi globally, found on every inhabited continent.",
  },
  {
    id: "amanita-fulva",
    scientificName: "Amanita fulva",
    commonName: "Tawny Grisette",
    aliases: ["Tawny Ringless Amanita"],
    synonyms: [],
    taxonomy: { kingdom: "Fungi", phylum: "Basidiomycota", class: "Agaricomycetes", order: "Agaricales", family: "Amanitaceae", genus: "Amanita", species: "fulva" },
    edibility: "edible",
    ecology: "mycorrhizal",
    habitat: "Deciduous and mixed forests with birch and oak",
    naRange: "Widespread across North America",
    morphology: { capShape: "Bell-shaped to convex, tawny-orange, striate margin, no ring", gillAttachment: "Free", sporeColor: "White", hasRing: false, hasVolva: true },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/13024/medium.jpg",
    imageAttribution: "© Amadej Trnkoczy / iNaturalist CC-BY-NC",
    crossSectionUrl: null,
    gbifId: 5284023,
    rarity: 35,
    fame: 40,
    difficulty: "hard",
    funFact: "Grisettes are Amanitas without a ring — they fruit from an egg-like volva and the stipe has no annulus, making them easier to identify.",
  },
  {
    id: "amanita-vaginata",
    scientificName: "Amanita vaginata",
    commonName: "Grisette",
    aliases: ["Grey Grisette", "Sheathed Amanita"],
    synonyms: [],
    taxonomy: { kingdom: "Fungi", phylum: "Basidiomycota", class: "Agaricomycetes", order: "Agaricales", family: "Amanitaceae", genus: "Amanita", species: "vaginata" },
    edibility: "edible",
    ecology: "mycorrhizal",
    habitat: "Mixed and deciduous forests; birch, oak, and alder",
    naRange: "Common across North America",
    morphology: { capShape: "Bell-shaped to convex, grey with striate margin and prominent grey volva; no ring", gillAttachment: "Free", sporeColor: "White", hasRing: false, hasVolva: true },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/3564/medium.jpg",
    imageAttribution: "© Amadej Trnkoczy / iNaturalist CC-BY-NC",
    crossSectionUrl: null,
    gbifId: 5284059,
    rarity: 35,
    fame: 40,
    difficulty: "hard",
    funFact: "Must be well cooked before eating — like most Amanitas, it is significantly more digestible when heated through completely.",
  },
  {
    id: "amanita-virosa",
    scientificName: "Amanita virosa",
    commonName: "European Destroying Angel",
    aliases: ["Destroying Angel", "Spring Destroying Angel"],
    synonyms: [],
    taxonomy: { kingdom: "Fungi", phylum: "Basidiomycota", class: "Agaricomycetes", order: "Agaricales", family: "Amanitaceae", genus: "Amanita", species: "virosa" },
    edibility: "deadly",
    ecology: "mycorrhizal",
    habitat: "Mixed and conifer forests in Europe and North America",
    naRange: "Northern North America; primarily a European species",
    morphology: { capShape: "Convex, pure white; slimy cap, ring, and large cup-shaped volva", gillAttachment: "Free", sporeColor: "White", hasRing: true, hasVolva: true },
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Amanita_virosa.jpg/400px-Amanita_virosa.jpg",
    imageAttribution: "© Tomasz Przechlewski / Wikimedia Commons CC-BY",
    crossSectionUrl: null,
    gbifId: 5284061,
    rarity: 55,
    fame: 60,
    difficulty: "medium",
    funFact: "Contains the same lethal amatoxins as A. phalloides; the all-white form makes it especially dangerous when misidentified as an edible species.",
  },
  {
    id: "amanita-citrina",
    scientificName: "Amanita citrina",
    commonName: "False Death Cap",
    aliases: ["Citron Amanita", "Lemon Amanita"],
    synonyms: ["Amanita mappa"],
    taxonomy: { kingdom: "Fungi", phylum: "Basidiomycota", class: "Agaricomycetes", order: "Agaricales", family: "Amanitaceae", genus: "Amanita", species: "citrina" },
    edibility: "inedible",
    ecology: "mycorrhizal",
    habitat: "Deciduous and mixed forests; oak and beech",
    naRange: "Eastern North America and Pacific Northwest",
    morphology: { capShape: "Convex, pale lemon-yellow, with flat pale patches; distinctive raw potato smell", gillAttachment: "Free", sporeColor: "White", hasRing: true, hasVolva: true },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/8560/medium.jpg",
    imageAttribution: "© Amadej Trnkoczy / iNaturalist CC-BY-NC",
    crossSectionUrl: null,
    gbifId: 5284011,
    rarity: 30,
    fame: 35,
    difficulty: "hard",
    funFact: "Despite its scary name 'False Death Cap,' it is merely inedible — it smells of raw potatoes but lacks the deadly amatoxins of true death caps.",
  },
  {
    id: "lepiota-cristata",
    scientificName: "Lepiota cristata",
    commonName: "Stinking Dapperling",
    aliases: ["Crested Lepiota", "Malodorous Lepiota"],
    synonyms: [],
    taxonomy: { kingdom: "Fungi", phylum: "Basidiomycota", class: "Agaricomycetes", order: "Agaricales", family: "Agaricaceae", genus: "Lepiota", species: "cristata" },
    edibility: "toxic",
    ecology: "saprotrophic",
    habitat: "Woodland paths, grass, gardens, and roadsides",
    naRange: "Common across North America",
    morphology: { capShape: "White convex cap with concentric reddish-brown scales; smells unpleasantly of rubber", gillAttachment: "Free", sporeColor: "White", hasRing: true, hasVolva: false },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/36890/medium.jpg",
    imageAttribution: "© Amadej Trnkoczy / iNaturalist CC-BY-NC",
    crossSectionUrl: null,
    gbifId: 2534692,
    rarity: 25,
    fame: 25,
    difficulty: "hard",
    funFact: "Many small Lepiota species contain deadly amatoxins in concentrations that can be fatal even in small amounts — none should be eaten.",
  },
  {
    id: "mycena-haematopus",
    scientificName: "Mycena haematopus",
    commonName: "Bleeding Mycena",
    aliases: ["Burgundy Bonnet", "Bleeding Bonnet"],
    synonyms: [],
    taxonomy: { kingdom: "Fungi", phylum: "Basidiomycota", class: "Agaricomycetes", order: "Agaricales", family: "Mycenaceae", genus: "Mycena", species: "haematopus" },
    edibility: "inedible",
    ecology: "saprotrophic",
    habitat: "On decaying hardwood logs and stumps, usually in clusters",
    naRange: "Very common across North America",
    morphology: { capShape: "Bell-shaped, wine-red to pinkish; bleeds deep red latex from broken stem", gillAttachment: "Adnate", sporeColor: "White", hasRing: false, hasVolva: false },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/7489/medium.jpg",
    imageAttribution: "© Jason Hollinger / iNaturalist CC-BY",
    crossSectionUrl: null,
    gbifId: 2534997,
    rarity: 25,
    fame: 35,
    difficulty: "hard",
    funFact: "The vivid red 'blood' that drips from a broken stem is caused by pigment-containing cells in the stem tissue, not true blood vessels.",
  },
  // ── More Boletales ────────────────────────────────────────────────────────
  {
    id: "paxillus-involutus",
    scientificName: "Paxillus involutus",
    commonName: "Brown Rollrim",
    aliases: ["Common Rollrim", "Poison Pax"],
    synonyms: [],
    taxonomy: { kingdom: "Fungi", phylum: "Basidiomycota", class: "Agaricomycetes", order: "Boletales", family: "Paxillaceae", genus: "Paxillus", species: "involutus" },
    edibility: "deadly",
    ecology: "mycorrhizal",
    habitat: "Birch and mixed forests; also in gardens near birch",
    naRange: "Common across northern North America",
    morphology: { capShape: "Convex with persistently inrolled margin, olive-brown; gills easily detach, bruise brown", gillAttachment: "Decurrent", sporeColor: "Brown", hasRing: false, hasVolva: false },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/31489/medium.jpg",
    imageAttribution: "© Amadej Trnkoczy / iNaturalist CC-BY-NC",
    crossSectionUrl: null,
    gbifId: 2534352,
    rarity: 20,
    fame: 50,
    difficulty: "medium",
    funFact: "Was eaten in Eastern Europe for centuries, but is now known to cause fatal immune hemolysis — the immune system attacks red blood cells — after repeated exposure.",
  },
  {
    id: "xerocomellus-chrysenteron",
    scientificName: "Xerocomellus chrysenteron",
    commonName: "Red Cracking Bolete",
    aliases: ["Common Cracked Bolete"],
    synonyms: ["Boletus chrysenteron", "Xerocomus chrysenteron"],
    taxonomy: { kingdom: "Fungi", phylum: "Basidiomycota", class: "Agaricomycetes", order: "Boletales", family: "Boletaceae", genus: "Xerocomellus", species: "chrysenteron" },
    edibility: "edible",
    ecology: "mycorrhizal",
    habitat: "Deciduous and mixed woodland with oak, beech, and hazel",
    naRange: "Eastern North America; more common in Europe",
    morphology: { capShape: "Convex, olive-brown to red-brown; cap cuticle cracks to reveal red flesh; pores yellow", gillAttachment: "Tubes/pores", sporeColor: "Olive-brown", hasRing: false, hasVolva: false },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/41843/medium.jpg",
    imageAttribution: "© Amadej Trnkoczy / iNaturalist CC-BY-NC",
    crossSectionUrl: null,
    gbifId: 5954002,
    rarity: 25,
    fame: 35,
    difficulty: "hard",
    funFact: "The cracked cap revealing red flesh underneath is its most distinctive feature — as if the skin of the mushroom has dried and split.",
  },
  {
    id: "leccinum-aurantiacum",
    scientificName: "Leccinum aurantiacum",
    commonName: "Orange Birch Bolete",
    aliases: ["Red-capped Scaber Stalk", "Orange Oak Bolete"],
    synonyms: [],
    taxonomy: { kingdom: "Fungi", phylum: "Basidiomycota", class: "Agaricomycetes", order: "Boletales", family: "Boletaceae", genus: "Leccinum", species: "aurantiacum" },
    edibility: "edible",
    ecology: "mycorrhizal",
    habitat: "With aspen (Populus) and sometimes oak; occasional with birch",
    naRange: "Widespread across northern North America",
    morphology: { capShape: "Convex, vivid orange-red; stalk with dark scabers; flesh turns grey-black when cut", gillAttachment: "Tubes/pores", sporeColor: "Brown", hasRing: false, hasVolva: false },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/29034/medium.jpg",
    imageAttribution: "© Amadej Trnkoczy / iNaturalist CC-BY-NC",
    crossSectionUrl: null,
    gbifId: 7892430,
    rarity: 40,
    fame: 40,
    difficulty: "hard",
    funFact: "The flesh turns grey and then black when cut or bruised — an unusual reaction caused by oxidizing enzymes that is harmless and doesn't affect flavor.",
  },
  {
    id: "suillus-granulatus",
    scientificName: "Suillus granulatus",
    commonName: "Granulated Bolete",
    aliases: ["Weeping Bolete", "Dotted-stem Suillus"],
    synonyms: [],
    taxonomy: { kingdom: "Fungi", phylum: "Basidiomycota", class: "Agaricomycetes", order: "Boletales", family: "Suillaceae", genus: "Suillus", species: "granulatus" },
    edibility: "edible",
    ecology: "mycorrhizal",
    habitat: "Pine forests; associated exclusively with pines",
    naRange: "Common across North America wherever pines grow",
    morphology: { capShape: "Convex, honey-yellow to tawny, slimy; pores exude white milk droplets when young", gillAttachment: "Tubes/pores", sporeColor: "Pale brown", hasRing: false, hasVolva: false },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/49372/medium.jpg",
    imageAttribution: "© Amadej Trnkoczy / iNaturalist CC-BY-NC",
    crossSectionUrl: null,
    gbifId: 5953909,
    rarity: 25,
    fame: 35,
    difficulty: "hard",
    funFact: "Young pores weep milky droplets of spore-containing fluid — this milky exudate is characteristic and a reliable identification feature.",
  },
  {
    id: "caloboletus-calopus",
    scientificName: "Caloboletus calopus",
    commonName: "Bitter Beech Bolete",
    aliases: ["Scarletina Bolete", "Bitter Bolete"],
    synonyms: ["Boletus calopus"],
    taxonomy: { kingdom: "Fungi", phylum: "Basidiomycota", class: "Agaricomycetes", order: "Boletales", family: "Boletaceae", genus: "Caloboletus", species: "calopus" },
    edibility: "inedible",
    ecology: "mycorrhizal",
    habitat: "Beech and mixed conifer-deciduous forests on acidic soils",
    naRange: "Eastern North America and Pacific Northwest",
    morphology: { capShape: "Convex, pale grey-brown; pores vivid red; stalk red-yellow with red reticulation; bruises blue", gillAttachment: "Tubes/pores", sporeColor: "Olive", hasRing: false, hasVolva: false },
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Caloboletus_calopus_2011_G3.jpg/400px-Caloboletus_calopus_2011_G3.jpg",
    imageAttribution: "© Gerhard Koller / Wikimedia Commons CC-BY-SA",
    crossSectionUrl: null,
    gbifId: 7890082,
    rarity: 50,
    fame: 25,
    difficulty: "hard",
    funFact: "Despite its attractive appearance with bright red pores, it is intensely bitter — the taste is enough to discourage consumption without danger.",
  },
  {
    id: "tapinella-atrotomentosa",
    scientificName: "Tapinella atrotomentosa",
    commonName: "Velvet Rollrim",
    aliases: ["Velvet Roll-rim", "Tomentose Rollrim"],
    synonyms: ["Paxillus atrotomentosus"],
    taxonomy: { kingdom: "Fungi", phylum: "Basidiomycota", class: "Agaricomycetes", order: "Boletales", family: "Tapinellaceae", genus: "Tapinella", species: "atrotomentosa" },
    edibility: "inedible",
    ecology: "saprotrophic",
    habitat: "On conifer stumps and buried conifer roots",
    naRange: "Widespread across North America in conifer forests",
    morphology: { capShape: "Convex with inrolled margin, yellow-brown; thick velvety dark brown stem", gillAttachment: "Decurrent", sporeColor: "Yellow-brown", hasRing: false, hasVolva: false },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/36892/medium.jpg",
    imageAttribution: "© Jason Hollinger / iNaturalist CC-BY",
    crossSectionUrl: null,
    gbifId: 2533049,
    rarity: 40,
    fame: 25,
    difficulty: "hard",
    funFact: "Its thick velvet-black stem is diagnostic — no other species looks quite like it; despite being a Boletales member it has gills rather than pores.",
  },
  {
    id: "gyroporus-castaneus",
    scientificName: "Gyroporus castaneus",
    commonName: "Chestnut Bolete",
    aliases: ["Bay Brown Bolete"],
    synonyms: [],
    taxonomy: { kingdom: "Fungi", phylum: "Basidiomycota", class: "Agaricomycetes", order: "Boletales", family: "Gyroporaceae", genus: "Gyroporus", species: "castaneus" },
    edibility: "choice",
    ecology: "mycorrhizal",
    habitat: "Deciduous woodland with oak and chestnut on sandy soils",
    naRange: "Eastern North America",
    morphology: { capShape: "Convex, chestnut-brown; white pores; stem hollow when mature, same color as cap", gillAttachment: "Tubes/pores", sporeColor: "Pale yellow", hasRing: false, hasVolva: false },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/53890/medium.jpg",
    imageAttribution: "© Jason Hollinger / iNaturalist CC-BY",
    crossSectionUrl: null,
    gbifId: 5953789,
    rarity: 45,
    fame: 25,
    difficulty: "hard",
    funFact: "Unlike most boletes, its stem becomes hollow when mature — a useful field mark that sets the Gyroporus genus apart.",
  },
  // ── More Polyporales ──────────────────────────────────────────────────────
  {
    id: "cerioporus-squamosus",
    scientificName: "Cerioporus squamosus",
    commonName: "Dryad's Saddle",
    aliases: ["Pheasant's Back Mushroom", "Hawk-wing Polypore"],
    synonyms: ["Polyporus squamosus"],
    taxonomy: { kingdom: "Fungi", phylum: "Basidiomycota", class: "Agaricomycetes", order: "Polyporales", family: "Polyporaceae", genus: "Cerioporus", species: "squamosus" },
    edibility: "edible",
    ecology: "saprotrophic",
    habitat: "On living and dead elms, maples, and other hardwoods",
    naRange: "Very common across eastern North America",
    morphology: { capShape: "Fan-shaped, pale cream with dark brown scales in concentric rings; large pores below", gillAttachment: "Tiny pores below", sporeColor: "White", hasRing: false, hasVolva: false },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/32892/medium.jpg",
    imageAttribution: "© Jason Hollinger / iNaturalist CC-BY",
    crossSectionUrl: null,
    gbifId: 5989192,
    rarity: 20,
    fame: 55,
    difficulty: "medium",
    funFact: "Smells distinctly of watermelon rind; best eaten when young and tender — older specimens become very tough and leathery.",
  },
  {
    id: "polyporus-brumalis",
    scientificName: "Polyporus brumalis",
    commonName: "Winter Polypore",
    aliases: ["Winter Bracket"],
    synonyms: [],
    taxonomy: { kingdom: "Fungi", phylum: "Basidiomycota", class: "Agaricomycetes", order: "Polyporales", family: "Polyporaceae", genus: "Polyporus", species: "brumalis" },
    edibility: "inedible",
    ecology: "saprotrophic",
    habitat: "On dead hardwood sticks and branches",
    naRange: "Common across North America",
    morphology: { capShape: "Convex circular, pale grey-brown; underside with white pores; centrally stalked", gillAttachment: "Tiny pores below", sporeColor: "White", hasRing: false, hasVolva: false },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/48130/medium.jpg",
    imageAttribution: "© Jason Hollinger / iNaturalist CC-BY",
    crossSectionUrl: null,
    gbifId: 5989171,
    rarity: 30,
    fame: 20,
    difficulty: "hard",
    funFact: "Fruits in winter and early spring (the name 'brumalis' means 'of winter') — its cold tolerance is unusual among wood-decaying polypores.",
  },
  {
    id: "trichaptum-biforme",
    scientificName: "Trichaptum biforme",
    commonName: "Violet Toothed Polypore",
    aliases: ["Purple Tooth Polypore"],
    synonyms: [],
    taxonomy: { kingdom: "Fungi", phylum: "Basidiomycota", class: "Agaricomycetes", order: "Polyporales", family: "Polyporaceae", genus: "Trichaptum", species: "biforme" },
    edibility: "inedible",
    ecology: "saprotrophic",
    habitat: "On dead and dying hardwoods, especially birch and maple",
    naRange: "Extremely common across all of North America",
    morphology: { capShape: "Fan-shaped brackets with greyish-white upper surface; pores purple-violet when fresh", gillAttachment: "Tiny pores/teeth below", sporeColor: "White", hasRing: false, hasVolva: false },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/29847/medium.jpg",
    imageAttribution: "© Jason Hollinger / iNaturalist CC-BY",
    crossSectionUrl: null,
    gbifId: 5989197,
    rarity: 10,
    fame: 30,
    difficulty: "hard",
    funFact: "One of the most common wood-decay fungi in eastern North America; the violet pores fade to white with age, making young specimens much more striking.",
  },
  {
    id: "pycnoporus-cinnabarinus",
    scientificName: "Pycnoporus cinnabarinus",
    commonName: "Cinnabar Bracket",
    aliases: ["Cinnabar Polypore", "Orange-red Bracket"],
    synonyms: [],
    taxonomy: { kingdom: "Fungi", phylum: "Basidiomycota", class: "Agaricomycetes", order: "Polyporales", family: "Polyporaceae", genus: "Pycnoporus", species: "cinnabarinus" },
    edibility: "inedible",
    ecology: "saprotrophic",
    habitat: "On dead hardwood, especially in sunny locations",
    naRange: "Common across North America",
    morphology: { capShape: "Fan-shaped bracket, vivid cinnabar-red to orange throughout; tiny pores", gillAttachment: "Tiny pores below", sporeColor: "White", hasRing: false, hasVolva: false },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/4830/medium.jpg",
    imageAttribution: "© Jason Hollinger / iNaturalist CC-BY",
    crossSectionUrl: null,
    gbifId: 5989162,
    rarity: 25,
    fame: 30,
    difficulty: "hard",
    funFact: "Its brilliant cinnabar-red color is produced by cinnabarinic acid, which is being studied as an antimicrobial compound against drug-resistant bacteria.",
  },
  {
    id: "daedaleopsis-confragosa",
    scientificName: "Daedaleopsis confragosa",
    commonName: "Blushing Bracket",
    aliases: ["Thin-walled Maze Polypore"],
    synonyms: [],
    taxonomy: { kingdom: "Fungi", phylum: "Basidiomycota", class: "Agaricomycetes", order: "Polyporales", family: "Polyporaceae", genus: "Daedaleopsis", species: "confragosa" },
    edibility: "inedible",
    ecology: "saprotrophic",
    habitat: "On dead hardwoods, especially willow, alder, and birch",
    naRange: "Common across North America",
    morphology: { capShape: "Fan-shaped bracket, grey-brown; pores elongated maze-like, blush pink when bruised", gillAttachment: "Maze-like pores below", sporeColor: "White", hasRing: false, hasVolva: false },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/39048/medium.jpg",
    imageAttribution: "© Jason Hollinger / iNaturalist CC-BY",
    crossSectionUrl: null,
    gbifId: 5989108,
    rarity: 25,
    fame: 25,
    difficulty: "hard",
    funFact: "The pore surface turns pink when bruised — hence 'blushing' — a reaction caused by a phenolic pigment that oxidizes on contact with air.",
  },
  {
    id: "daedalea-quercina",
    scientificName: "Daedalea quercina",
    commonName: "Oak Mazegill",
    aliases: ["Thick Maze Oak Polypore"],
    synonyms: [],
    taxonomy: { kingdom: "Fungi", phylum: "Basidiomycota", class: "Agaricomycetes", order: "Polyporales", family: "Fomitopsidaceae", genus: "Daedalea", species: "quercina" },
    edibility: "inedible",
    ecology: "saprotrophic",
    habitat: "On dead oaks and other hardwoods; causes brown rot",
    naRange: "Eastern North America",
    morphology: { capShape: "Thick, hoof-shaped bracket, pale tan to grey-buff; underside labyrinthine maze of thick walls", gillAttachment: "Maze-like pores below", sporeColor: "White", hasRing: false, hasVolva: false },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/14842/medium.jpg",
    imageAttribution: "© Jason Hollinger / iNaturalist CC-BY",
    crossSectionUrl: null,
    gbifId: 5989107,
    rarity: 30,
    fame: 35,
    difficulty: "hard",
    funFact: "Its pore surface is a three-dimensional labyrinth — the maze-like structure maximizes spore-releasing surface area within a compact structure.",
  },
  {
    id: "bjerkandera-adusta",
    scientificName: "Bjerkandera adusta",
    commonName: "Smoky Bracket",
    aliases: ["Smoky Polypore"],
    synonyms: [],
    taxonomy: { kingdom: "Fungi", phylum: "Basidiomycota", class: "Agaricomycetes", order: "Polyporales", family: "Meruliaceae", genus: "Bjerkandera", species: "adusta" },
    edibility: "inedible",
    ecology: "saprotrophic",
    habitat: "On dead hardwoods and occasionally conifers",
    naRange: "Very common across North America",
    morphology: { capShape: "Fan-shaped, white to grey; grey-black tiny pores; thin flexible bracket", gillAttachment: "Tiny pores below", sporeColor: "White", hasRing: false, hasVolva: false },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/43890/medium.jpg",
    imageAttribution: "© Jason Hollinger / iNaturalist CC-BY",
    crossSectionUrl: null,
    gbifId: 5989064,
    rarity: 15,
    fame: 20,
    difficulty: "hard",
    funFact: "Produces a unique grey-black pore surface from melanin — the same pigment as in human skin; its enzymes are studied for bioremediation of dyes.",
  },
  {
    id: "hapalopilus-nidulans",
    scientificName: "Hapalopilus nidulans",
    commonName: "Cinnamon Bracket",
    aliases: ["Tender Nesting Polypore"],
    synonyms: ["Hapalopilus rutilans"],
    taxonomy: { kingdom: "Fungi", phylum: "Basidiomycota", class: "Agaricomycetes", order: "Polyporales", family: "Polyporaceae", genus: "Hapalopilus", species: "nidulans" },
    edibility: "toxic",
    ecology: "saprotrophic",
    habitat: "On dead hardwood trees including oak, beech, and willow",
    naRange: "Eastern North America",
    morphology: { capShape: "Semicircular soft bracket, warm cinnamon-orange throughout; turns vivid purple with KOH", gillAttachment: "Tiny pores below", sporeColor: "White", hasRing: false, hasVolva: false },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/53249/medium.jpg",
    imageAttribution: "© Jason Hollinger / iNaturalist CC-BY",
    crossSectionUrl: null,
    gbifId: 5989130,
    rarity: 45,
    fame: 20,
    difficulty: "hard",
    funFact: "Contains polyporic acid — it turns bright purple when potassium hydroxide (KOH) is applied; ingestion causes kidney failure and a purple discoloration of urine.",
  },
  // ── More Russulales ───────────────────────────────────────────────────────
  {
    id: "russula-virescens",
    scientificName: "Russula virescens",
    commonName: "Green Brittlegill",
    aliases: ["Quilted Green Russula", "Green Cracked Russula"],
    synonyms: [],
    taxonomy: { kingdom: "Fungi", phylum: "Basidiomycota", class: "Agaricomycetes", order: "Russulales", family: "Russulaceae", genus: "Russula", species: "virescens" },
    edibility: "choice",
    ecology: "mycorrhizal",
    habitat: "Deciduous forests with oak and beech",
    naRange: "Eastern North America",
    morphology: { capShape: "Convex, greenish cap breaking into irregular patches revealing white skin; brittle gills", gillAttachment: "Adnate", sporeColor: "White", hasRing: false, hasVolva: false },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/18030/medium.jpg",
    imageAttribution: "© Jason Hollinger / iNaturalist CC-BY",
    crossSectionUrl: null,
    gbifId: 5245762,
    rarity: 40,
    fame: 45,
    difficulty: "hard",
    funFact: "The cracked green cap is diagnostic — no other common green mushroom has this 'quilted' pattern; considered one of the finest edible Russulas.",
  },
  {
    id: "russula-cyanoxantha",
    scientificName: "Russula cyanoxantha",
    commonName: "Charcoal Burner",
    aliases: ["Variable Russula"],
    synonyms: [],
    taxonomy: { kingdom: "Fungi", phylum: "Basidiomycota", class: "Agaricomycetes", order: "Russulales", family: "Russulaceae", genus: "Russula", species: "cyanoxantha" },
    edibility: "choice",
    ecology: "mycorrhizal",
    habitat: "Broad-leaved woodland with oak, beech, and hazel",
    naRange: "Eastern North America",
    morphology: { capShape: "Convex, variable — violet-grey to olive-green to lilac; gills white, greasy to touch", gillAttachment: "Adnate", sporeColor: "White", hasRing: false, hasVolva: false },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/24030/medium.jpg",
    imageAttribution: "© Amadej Trnkoczy / iNaturalist CC-BY-NC",
    crossSectionUrl: null,
    gbifId: 5245690,
    rarity: 30,
    fame: 45,
    difficulty: "hard",
    funFact: "The most variable Russula in cap color; the greasy (non-brittle) gill texture distinguishes it from similar species.",
  },
  {
    id: "russula-foetens",
    scientificName: "Russula foetens",
    commonName: "Stinking Brittlegill",
    aliases: ["Fetid Russula"],
    synonyms: [],
    taxonomy: { kingdom: "Fungi", phylum: "Basidiomycota", class: "Agaricomycetes", order: "Russulales", family: "Russulaceae", genus: "Russula", species: "foetens" },
    edibility: "toxic",
    ecology: "mycorrhizal",
    habitat: "Deciduous and mixed woodland, often in damp areas",
    naRange: "Widespread across North America",
    morphology: { capShape: "Convex to flat, honey-yellow to ochre, striate margin; oily fetid rancid smell", gillAttachment: "Adnate", sporeColor: "Cream", hasRing: false, hasVolva: false },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/58490/medium.jpg",
    imageAttribution: "© Amadej Trnkoczy / iNaturalist CC-BY-NC",
    crossSectionUrl: null,
    gbifId: 5245704,
    rarity: 25,
    fame: 30,
    difficulty: "hard",
    funFact: "Its rancid, oily smell — like motor oil or old dish water — is overpowering and makes it one of the most easily identified Russulas by scent alone.",
  },
  {
    id: "lactarius-torminosus",
    scientificName: "Lactarius torminosus",
    commonName: "Woolly Milk Cap",
    aliases: ["Pink-fringed Milk Cap", "Birch Milk Cap"],
    synonyms: [],
    taxonomy: { kingdom: "Fungi", phylum: "Basidiomycota", class: "Agaricomycetes", order: "Russulales", family: "Russulaceae", genus: "Lactarius", species: "torminosus" },
    edibility: "toxic",
    ecology: "mycorrhizal",
    habitat: "Birch forests and mixed woodland with birch",
    naRange: "Northern North America wherever birch grows",
    morphology: { capShape: "Convex with persistently inrolled woolly-fringed margin, salmon-pink with concentric zones; white acrid latex", gillAttachment: "Decurrent", sporeColor: "Pale cream", hasRing: false, hasVolva: false },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/24348/medium.jpg",
    imageAttribution: "© Amadej Trnkoczy / iNaturalist CC-BY-NC",
    crossSectionUrl: null,
    gbifId: 5245810,
    rarity: 30,
    fame: 35,
    difficulty: "hard",
    funFact: "Causes severe gastric cramps (hence 'torminosus' = griping) but is eaten pickled in Scandinavia after lengthy preparation to neutralize the acrid compounds.",
  },
  {
    id: "lactarius-piperatus",
    scientificName: "Lactarius piperatus",
    commonName: "Peppery Milk Cap",
    aliases: ["Peppery Lactarius"],
    synonyms: [],
    taxonomy: { kingdom: "Fungi", phylum: "Basidiomycota", class: "Agaricomycetes", order: "Russulales", family: "Russulaceae", genus: "Lactarius", species: "piperatus" },
    edibility: "inedible",
    ecology: "mycorrhizal",
    habitat: "Deciduous and mixed woodland, especially with oak and beech",
    naRange: "Eastern North America",
    morphology: { capShape: "Convex to vase-shaped, pure white, smooth, dry; crowded white gills; acrid white latex", gillAttachment: "Decurrent", sporeColor: "White to pale cream", hasRing: false, hasVolva: false },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/63490/medium.jpg",
    imageAttribution: "© Amadej Trnkoczy / iNaturalist CC-BY-NC",
    crossSectionUrl: null,
    gbifId: 5245805,
    rarity: 30,
    fame: 30,
    difficulty: "hard",
    funFact: "Has the most intensely acrid latex of any Lactarius — the burning peppery taste is caused by sesquiterpene compounds and lingers for minutes.",
  },
  {
    id: "lactarius-volemus",
    scientificName: "Lactarius volemus",
    commonName: "Fishy Milk Cap",
    aliases: ["Weeping Milk Cap", "Bradley"],
    synonyms: [],
    taxonomy: { kingdom: "Fungi", phylum: "Basidiomycota", class: "Agaricomycetes", order: "Russulales", family: "Russulaceae", genus: "Lactarius", species: "volemus" },
    edibility: "edible",
    ecology: "mycorrhizal",
    habitat: "Broad-leaved and mixed forests; oak, beech, hornbeam",
    naRange: "Eastern North America",
    morphology: { capShape: "Convex, dry, tawny-orange to russet; copious white latex that dries brown; fishy smell", gillAttachment: "Decurrent", sporeColor: "White to cream", hasRing: false, hasVolva: false },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/43029/medium.jpg",
    imageAttribution: "© Jason Hollinger / iNaturalist CC-BY",
    crossSectionUrl: null,
    gbifId: 5245820,
    rarity: 40,
    fame: 30,
    difficulty: "hard",
    funFact: "Bleeds copious white latex when cut that quickly browns and dries; the strong fishy or herring-like smell is unique among woodland mushrooms.",
  },
  {
    id: "hericium-coralloides",
    scientificName: "Hericium coralloides",
    commonName: "Coral Tooth",
    aliases: ["Comb Tooth", "Branched Hedgehog"],
    synonyms: [],
    taxonomy: { kingdom: "Fungi", phylum: "Basidiomycota", class: "Agaricomycetes", order: "Russulales", family: "Hericiaceae", genus: "Hericium", species: "coralloides" },
    edibility: "choice",
    ecology: "saprotrophic",
    habitat: "On dead and dying hardwoods, especially beech and oak",
    naRange: "Eastern North America",
    morphology: { capShape: "White branching coral with downward-pointing teeth on branch tips; no main cap", gillAttachment: "Spines/teeth", sporeColor: "White", hasRing: false, hasVolva: false },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/3849/medium.jpg",
    imageAttribution: "© Jason Hollinger / iNaturalist CC-BY",
    crossSectionUrl: null,
    gbifId: 2553571,
    rarity: 55,
    fame: 50,
    difficulty: "medium",
    funFact: "Unlike Lion's Mane (H. erinaceus), the teeth here grow on branching coral-like arms rather than hanging in a single mass — making it easier to identify.",
  },
  // ── More Ascomycota ───────────────────────────────────────────────────────
  {
    id: "aleuria-aurantia",
    scientificName: "Aleuria aurantia",
    commonName: "Orange Peel Fungus",
    aliases: ["Orange Fairy Cup", "Orange Cup Fungus"],
    synonyms: [],
    taxonomy: { kingdom: "Fungi", phylum: "Ascomycota", class: "Pezizomycetes", order: "Pezizales", family: "Pyronemataceae", genus: "Aleuria", species: "aurantia" },
    edibility: "edible",
    ecology: "saprotrophic",
    habitat: "Bare soil on disturbed ground, roadsides, gardens, and wood chips",
    naRange: "Common across North America",
    morphology: { capShape: "Cup to saucer-shaped, vivid orange inside, whitish and powdery outside", gillAttachment: "None (cup fungus)", sporeColor: "White", hasRing: false, hasVolva: false },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/4829/medium.jpg",
    imageAttribution: "© Jason Hollinger / iNaturalist CC-BY",
    crossSectionUrl: null,
    gbifId: 3268458,
    rarity: 30,
    fame: 65,
    difficulty: "medium",
    funFact: "Almost looks artificial — its brilliant orange color exactly mimics a discarded orange peel, which has led to it being called 'Orange Peel Fungus.'",
  },
  {
    id: "daldinia-concentrica",
    scientificName: "Daldinia concentrica",
    commonName: "King Alfred's Cakes",
    aliases: ["Carbon Balls", "Cramp Balls"],
    synonyms: [],
    taxonomy: { kingdom: "Fungi", phylum: "Ascomycota", class: "Sordariomycetes", order: "Xylariales", family: "Xylariaceae", genus: "Daldinia", species: "concentrica" },
    edibility: "inedible",
    ecology: "saprotrophic",
    habitat: "On dead ash and other hardwood trees",
    naRange: "Common across North America",
    morphology: { capShape: "Round to irregular, shiny black exterior; silver-and-black concentric rings inside", gillAttachment: "None (stromata)", sporeColor: "Black", hasRing: false, hasVolva: false },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/18392/medium.jpg",
    imageAttribution: "© Jason Hollinger / iNaturalist CC-BY",
    crossSectionUrl: null,
    gbifId: 3269882,
    rarity: 25,
    fame: 45,
    difficulty: "medium",
    funFact: "The purple-black balls can smolder for hours, making them a traditional fire-starter; cross-section reveals beautiful alternating metallic rings.",
  },
  {
    id: "bulgaria-inquinans",
    scientificName: "Bulgaria inquinans",
    commonName: "Black Bulgar",
    aliases: ["Bachelor's Buttons"],
    synonyms: [],
    taxonomy: { kingdom: "Fungi", phylum: "Ascomycota", class: "Leotiomycetes", order: "Helotiales", family: "Bulgariaceae", genus: "Bulgariaa", species: "inquinans" },
    edibility: "inedible",
    ecology: "saprotrophic",
    habitat: "Clustered on recently felled oak trunks and logs in autumn",
    naRange: "Eastern North America",
    morphology: { capShape: "Rubbery top-shaped black cup, gelatinous; black disc-shaped ascus surface", gillAttachment: "None (cup fungus)", sporeColor: "Black", hasRing: false, hasVolva: false },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/27049/medium.jpg",
    imageAttribution: "© Jason Hollinger / iNaturalist CC-BY",
    crossSectionUrl: null,
    gbifId: 3268637,
    rarity: 30,
    fame: 25,
    difficulty: "hard",
    funFact: "Named 'inquinans' because touching the black discs leaves an indelible black stain on fingers — caused by the black spore mass.",
  },
  {
    id: "rhytisma-acerinum",
    scientificName: "Rhytisma acerinum",
    commonName: "Tar Spot",
    aliases: ["Maple Tar Spot", "Black Spot"],
    synonyms: [],
    taxonomy: { kingdom: "Fungi", phylum: "Ascomycota", class: "Leotiomycetes", order: "Rhytismatales", family: "Rhytismataceae", genus: "Rhytisma", species: "acerinum" },
    edibility: "inedible",
    ecology: "parasitic",
    habitat: "On living maple (Acer) leaves; overwinters on fallen leaves",
    naRange: "Extremely common across North America wherever maples grow",
    morphology: { capShape: "Glossy black raised tar-like spots on maple leaves; irregular outline", gillAttachment: "None (leaf pathogen)", sporeColor: "Cream", hasRing: false, hasVolva: false },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/18483/medium.jpg",
    imageAttribution: "© Jason Hollinger / iNaturalist CC-BY",
    crossSectionUrl: null,
    gbifId: 3267780,
    rarity: 10,
    fame: 40,
    difficulty: "hard",
    funFact: "The spots look like drops of tar burned into the leaf; nearly every maple tree in North America is infected, yet the fungus rarely kills its host.",
  },
  {
    id: "claviceps-purpurea",
    scientificName: "Claviceps purpurea",
    commonName: "Ergot",
    aliases: ["Rye Ergot", "Ryecorn Ergot"],
    synonyms: [],
    taxonomy: { kingdom: "Fungi", phylum: "Ascomycota", class: "Sordariomycetes", order: "Hypocreales", family: "Clavicipitaceae", genus: "Claviceps", species: "purpurea" },
    edibility: "deadly",
    ecology: "parasitic",
    habitat: "On rye, wheat, and wild grasses — replaces the grain with a hard purple-black sclerotium",
    naRange: "Widespread wherever grasses and cereals grow in North America",
    morphology: { capShape: "Hard purple-black elongated sclerotium replacing the grain; tiny club-shaped stromata in spring", gillAttachment: "None (sclerotium)", sporeColor: "White", hasRing: false, hasVolva: false },
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Claviceps_purpurea_02.jpg/400px-Claviceps_purpurea_02.jpg",
    imageAttribution: "© Dominique Jacquin / Wikimedia Commons CC-BY-SA",
    crossSectionUrl: null,
    gbifId: 3269840,
    rarity: 30,
    fame: 80,
    difficulty: "easy",
    funFact: "Ergot alkaloids caused the medieval plague 'St. Anthony's Fire'; they are also the basis for the synthesis of LSD, discovered by Albert Hofmann in 1943.",
  },
  {
    id: "trichoglossum-hirsutum",
    scientificName: "Trichoglossum hirsutum",
    commonName: "Hairy Earthtongue",
    aliases: ["Velvet Earthtongue"],
    synonyms: [],
    taxonomy: { kingdom: "Fungi", phylum: "Ascomycota", class: "Leotiomycetes", order: "Helotiales", family: "Geoglossaceae", genus: "Trichoglossum", species: "hirsutum" },
    edibility: "inedible",
    ecology: "saprotrophic",
    habitat: "Damp grassland, mossy areas, and woodland edges; often in short turf",
    naRange: "Common across North America",
    morphology: { capShape: "Black velvety club-shaped tongue, flattened head; densely hairy from stiff setae", gillAttachment: "None (club)", sporeColor: "Dark brown", hasRing: false, hasVolva: false },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/38940/medium.jpg",
    imageAttribution: "© Jason Hollinger / iNaturalist CC-BY",
    crossSectionUrl: null,
    gbifId: 3268748,
    rarity: 40,
    fame: 25,
    difficulty: "hard",
    funFact: "The earthtongues are an ancient lineage of ascomycetes; their tongue-like form is convergent with the unrelated Cudonia and Spathularia in other genera.",
  },
  {
    id: "leotia-lubrica",
    scientificName: "Leotia lubrica",
    commonName: "Jelly Baby",
    aliases: ["Slippery Cap", "Ochre Jelly Club"],
    synonyms: [],
    taxonomy: { kingdom: "Fungi", phylum: "Ascomycota", class: "Leotiomycetes", order: "Leotiales", family: "Leotiaceae", genus: "Leotia", species: "lubrica" },
    edibility: "inedible",
    ecology: "saprotrophic",
    habitat: "Damp woodland, often in groups in leaf litter and moss",
    naRange: "Common across North America",
    morphology: { capShape: "Gelatinous convex ochre-olive cap on gelatinous greenish stalk; rubbery and slimy", gillAttachment: "None (club/cap fungus)", sporeColor: "Cream", hasRing: false, hasVolva: false },
    imageUrl: "https://inaturalist-open-data.s3.amazonaws.com/photos/28930/medium.jpg",
    imageAttribution: "© Jason Hollinger / iNaturalist CC-BY",
    crossSectionUrl: null,
    gbifId: 3268624,
    rarity: 30,
    fame: 30,
    difficulty: "hard",
    funFact: "Named 'Jelly Baby' for its resemblance to the gelatinous candy; its slippery texture is caused by a gelatinized outer layer of tissue.",
  },
  {
    id: "hymenoscyphus-fraxineus",
    scientificName: "Hymenoscyphus fraxineus",
    commonName: "Ash Dieback Fungus",
    aliases: ["Chalara Ash Dieback"],
    synonyms: ["Chalara fraxinea"],
    taxonomy: { kingdom: "Fungi", phylum: "Ascomycota", class: "Leotiomycetes", order: "Helotiales", family: "Hymenoscyphaceae", genus: "Hymenoscyphus", species: "fraxineus" },
    edibility: "inedible",
    ecology: "parasitic",
    habitat: "On ash (Fraxinus) leaf rachises; deadly pathogen of European and North American ash trees",
    naRange: "Spreading across eastern North America; native to Asia",
    morphology: { capShape: "Tiny creamy-white cup fungi on blackened ash leaf stalks; 3-8mm diameter", gillAttachment: "None (cup fungus)", sporeColor: "White", hasRing: false, hasVolva: false },
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Hymenoscyphus_fraxineus_2.jpg/400px-Hymenoscyphus_fraxineus_2.jpg",
    imageAttribution: "© Owe Nilsson / Wikimedia Commons CC-BY-SA",
    crossSectionUrl: null,
    gbifId: 3266562,
    rarity: 20,
    fame: 50,
    difficulty: "medium",
    funFact: "Has killed over 100 million ash trees in Europe since 2006 and threatens to eliminate ash from North American forests — one of the most destructive plant pathogens ever recorded.",
  },
  // ── Mucoromycota ─────────────────────────────────────────────────────────
  {
    id: "cunninghamella-elegans",
    scientificName: "Cunninghamella elegans",
    commonName: "Elegant Cunninghamella",
    aliases: [],
    synonyms: [],
    taxonomy: { kingdom: "Fungi", phylum: "Mucoromycota", class: "Mucoromycetes", order: "Mucorales", family: "Cunninghamellaceae", genus: "Cunninghamella", species: "elegans" },
    edibility: "inedible",
    ecology: "saprotrophic",
    habitat: "Soil and decaying organic matter; cosmopolitan",
    naRange: "Widespread across warm regions of North America",
    morphology: { capShape: "White branching sporangiophores with globose spore-bearing vesicles", gillAttachment: "None (zygomycete)", sporeColor: "White", hasRing: false, hasVolva: false },
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Cunninghamella_elegans.jpg/400px-Cunninghamella_elegans.jpg",
    imageAttribution: "© Medmyco / Wikimedia Commons CC-BY-SA",
    crossSectionUrl: null,
    gbifId: 3267698,
    rarity: 50,
    fame: 15,
    difficulty: "hard",
    funFact: "Extensively used in pharmaceutical research as a 'microbial model' of mammalian drug metabolism — it converts drugs to metabolites just as the human liver does.",
  },
  // ── Chytridiomycota ───────────────────────────────────────────────────────
  {
    id: "batrachochytrium-dendrobatidis",
    scientificName: "Batrachochytrium dendrobatidis",
    commonName: "Chytrid Fungus",
    aliases: ["Frog Chytrid", "Amphibian Chytrid"],
    synonyms: [],
    taxonomy: { kingdom: "Fungi", phylum: "Chytridiomycota", class: "Chytridiomycetes", order: "Rhizophydiales", family: "Batrachochytriaceae", genus: "Batrachochytrium", species: "dendrobatidis" },
    edibility: "inedible",
    ecology: "parasitic",
    habitat: "Aquatic and semi-aquatic habitats worldwide; infects amphibian skin",
    naRange: "Widespread in moist environments across North America; particularly destructive in western mountains",
    morphology: { capShape: "Microscopic zoospore-producing thallus within amphibian skin cells", gillAttachment: "None (chytrid)", sporeColor: "N/A", hasRing: false, hasVolva: false },
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Batrachochytrium_dendrobatidis.jpg/400px-Batrachochytrium_dendrobatidis.jpg",
    imageAttribution: "© US Geological Survey / Wikimedia Commons CC0",
    crossSectionUrl: null,
    gbifId: 2538940,
    rarity: 40,
    fame: 60,
    difficulty: "medium",
    funFact: "Considered the most destructive vertebrate pathogen ever recorded — responsible for the decline or extinction of over 200 amphibian species worldwide.",
  },
  // ── Blastocladiomycota ────────────────────────────────────────────────────
  {
    id: "allomyces-reticulatus",
    scientificName: "Allomyces reticulatus",
    commonName: "Water Mold",
    aliases: [],
    synonyms: [],
    taxonomy: { kingdom: "Fungi", phylum: "Blastocladiomycota", class: "Blastocladiomycetes", order: "Blastocladiales", family: "Blastocladiaceae", genus: "Allomyces", species: "reticulatus" },
    edibility: "inedible",
    ecology: "saprotrophic",
    habitat: "Freshwater and moist soil; aquatic or semi-aquatic environments",
    naRange: "Tropical and subtropical regions of North America",
    morphology: { capShape: "Microscopic branching filamentous thallus with alternating diploid and haploid generations", gillAttachment: "None (chytrid-like)", sporeColor: "N/A", hasRing: false, hasVolva: false },
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Allomyces.jpg/400px-Allomyces.jpg",
    imageAttribution: "© Wikimedia Commons / Public Domain",
    crossSectionUrl: null,
    gbifId: 3267540,
    rarity: 75,
    fame: 10,
    difficulty: "hard",
    funFact: "Allomyces was the first organism shown to have a true alternation of generations (haploid and diploid phases) with flagellated gametes — a landmark in mycology.",
  },
];
